# to add/remove the specific package using loop
- name: add or remove the package
  hosts: web
  become: yes
  tasks:
  - name: add or remove the packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {name: 'nginx', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'zip', state: 'absent'}