- name: functions
  hosts: local
  connection: local
  vars:
    persons: "chanti,sreevani,gangi"
  tasks:
  - name: person information
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Mahi') }}"

  - name: person information separated by delimiter 
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert to upper
    vars:
      name: "mahi reddy"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to lower
    vars:
      name: "MAHI REDDY"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: map to list
    vars:
      course: 
        Duration: 120HR
        Trainer: "Maheswari"
    ansible.builtin.debug:
      msg: "Hello {{ course | dict2items }}"
  

  - name: list to Map
    vars:
      course: 
      - {'key': 'Duration','value': '120HR'}
      - {'key': 'Trainer', 'value': 'Maheswari'}
    ansible.builtin.debug:
      msg: "Hello {{ course | items2dict }}"

  - name: to check the ip address is correct or not
    vars:
      ip: 300.100.100.1
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"