- name: functions
  hosts: local
  connection: local
  vars:
    persons: "chanti,sreevani,gangi"
  tasks:
  - name: person information
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Mahi') }}"

  - name: person information separated by delimiter 
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert to upper
    vars:
      name: "mahi reddy"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to lower
    vars:
      name: "mahi reddy"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"