- name: User Creation
  hosts: local
  connection: local
  tasks:
  - name: Check Roboshop user exist or not
    ansible.builtin.command: id roboshop # here user not exist so we are handling this through error handling
    register: output
    ignore_errors: true

  - name: create user
    ansible.builtin.command: useradd roboshop # so creating the user
    when: output.rc != 0 # it means task failure

  - name: user already exists
    ansible.builtin.debug:
      msg: "User already exists"
    when: output.rc == 0 